name: Build and Release

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  GO_VERSION: '1.24'
  APP_NAME: 'shamsy-calendar'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: false
    
    - name: Download dependencies
      run: go mod download
    

  build:
    needs: test
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            name: linux-amd64
          - os: ubuntu-latest
            goos: linux
            goarch: arm64
            name: linux-arm64
          - os: ubuntu-latest
            goos: windows
            goarch: amd64
            name: windows-amd64
            ext: .exe
          - os: ubuntu-latest
            goos: darwin
            goarch: amd64
            name: darwin-amd64
          - os: ubuntu-latest
            goos: darwin
            goarch: arm64
            name: darwin-arm64
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: false
    
    - name: Get version
      id: version
      run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    
    - name: Build binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: 0
      run: |
        mkdir -p dist
        go build -ldflags="-s -w -X main.version=${{ steps.version.outputs.version }}" -o dist/${{ env.APP_NAME }}-${{ matrix.name }}${{ matrix.ext }} .
    
    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.APP_NAME }}-${{ matrix.name }}
        path: dist/${{ env.APP_NAME }}-${{ matrix.name }}${{ matrix.ext }}
        retention-days: 1

  package-linux:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Download binary
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.APP_NAME }}-linux-${{ matrix.arch }}
        path: .
    
    - name: Get version
      id: version
      run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    
    - name: Install packaging tools
      run: |
        sudo apt-get update
        sudo apt-get install -y dpkg-dev rpm
    
    - name: Create DEB package
      run: |
        VERSION="${{ steps.version.outputs.version }}"
        ARCH="${{ matrix.arch }}"
        PKG_DIR="deb-pkg"
        
        mkdir -p ${PKG_DIR}/DEBIAN
        mkdir -p ${PKG_DIR}/usr/bin
        
        # Copy binary
        cp ${{ env.APP_NAME }}-linux-${ARCH} ${PKG_DIR}/usr/bin/${{ env.APP_NAME }}
        chmod 755 ${PKG_DIR}/usr/bin/${{ env.APP_NAME }}
        
        # Create control file
        cat > ${PKG_DIR}/DEBIAN/control << EOF
        Package: ${{ env.APP_NAME }}
        Version: ${VERSION#v}
        Section: utils
        Priority: optional
        Architecture: ${ARCH}
        Maintainer: Developer <dev@example.com>
        Description: Persian Calendar CLI
         Command-line Persian calendar tool
        EOF
        
        # Build package
        dpkg-deb --build ${PKG_DIR} ${{ env.APP_NAME }}_${VERSION#v}_${ARCH}.deb
    
    - name: Create RPM package
      run: |
        VERSION="${{ steps.version.outputs.version }}"
        ARCH="${{ matrix.arch }}"
        
        mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
        mkdir -p ~/rpmbuild/BUILDROOT/usr/bin
        
        # Copy binary
        cp ${{ env.APP_NAME }}-linux-${ARCH} ~/rpmbuild/BUILDROOT/usr/bin/${{ env.APP_NAME }}
        chmod 755 ~/rpmbuild/BUILDROOT/usr/bin/${{ env.APP_NAME }}
        
        # Create spec file
        cat > ~/rpmbuild/SPECS/${{ env.APP_NAME }}.spec << EOF
        Name: ${{ env.APP_NAME }}
        Version: ${VERSION#v}
        Release: 1
        Summary: Persian Calendar CLI
        License: MIT
        
        %description
        Command-line Persian calendar tool
        
        %files
        /usr/bin/${{ env.APP_NAME }}
        
        %changelog
        * $(date "+%a %b %d %Y") Developer <dev@example.com> - ${VERSION#v}-1
        - Release ${VERSION}
        EOF
        
        # Build RPM
        rpmbuild --define "_topdir $HOME/rpmbuild" --define "_rpmdir ." -bb ~/rpmbuild/SPECS/${{ env.APP_NAME }}.spec
        find . -name "*.rpm" -exec mv {} ${{ env.APP_NAME }}-${VERSION#v}-1.${ARCH}.rpm \;
    
    - name: Upload packages
      uses: actions/upload-artifact@v4
      with:
        name: packages-${{ matrix.arch }}
        path: |
          *.deb
          *.rpm
        retention-days: 1

  release:
    needs: [build, package-linux]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        merge-multiple: true
    
    - name: List artifacts
      run: |
        echo "Downloaded artifacts:"
        find artifacts -type f -exec ls -la {} \;
    
    - name: Generate release notes
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        
        cat > release_notes.md << EOF
        ## Shamsy Calendar ${TAG_NAME}
        
        Persian (Solar Hijri) calendar CLI tool.
        
        ### Installation
        
        **Linux (DEB):**
        \`\`\`bash
        sudo dpkg -i shamsy-calendar_*_amd64.deb
        \`\`\`
        
        **Linux (RPM):**
        \`\`\`bash
        sudo rpm -i shamsy-calendar-*-1.amd64.rpm
        \`\`\`
        
        **Binary:**
        \`\`\`bash
        chmod +x shamsy-calendar-*
        sudo mv shamsy-calendar-* /usr/local/bin/shamsy-calendar
        \`\`\`
        
        ### Usage
        \`\`\`bash
        shamsy-calendar                    # Current month
        shamsy-calendar 1403               # Full year
        shamsy-calendar 1403 6             # Specific month
        shamsy-calendar 1403 6 --show-holidays  # With holidays
        \`\`\`
        EOF
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: artifacts/*
        body_path: release_notes.md
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
